// import "~/assets/globals.css";
import "~/assets/globals.scss";

export const metadata = {
  title: "Stravel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg--default">{children}</body>
    </html>
  );
}
